from __future__ import annotations

import os
from dataclasses import asdict, dataclass
from typing import Literal


CapabilityKind = Literal["prompt", "resource", "tool"]
AccessMode = Literal["read", "write", "dispatch", "adapter"]
PRODUCT_NAME = os.environ.get("NOGRA_PRODUCT_NAME") or os.environ.get("Y26_PRODUCT_NAME", "Nogra")
MCP_NAME = os.environ.get("NOGRA_MCP_NAME", f"{PRODUCT_NAME} MCP")


@dataclass(frozen=True)
class Capability:
    id: str
    kind: CapabilityKind
    title: str
    layer: str
    access: AccessMode
    status: str
    auth: str
    receipt: str
    description: str

    def to_dict(self) -> dict[str, str]:
        return asdict(self)


CAPABILITIES: tuple[Capability, ...] = (
    Capability(
        id="prompt.codex",
        kind="prompt",
        title="/codex fresh eyes",
        layer="CEO + Manager",
        access="read",
        status="ready",
        auth="local session / OAuth client",
        receipt="caller transcript",
        description="Direct CEO-called Codex conversation partner. Answers the caller's exact message without Manager synthesis.",
    ),
    Capability(
        id="prompt.codex_full",
        kind="prompt",
        title="/codex full",
        layer="CEO + Manager",
        access="read",
        status="ready",
        auth="local session / OAuth client",
        receipt="caller transcript + MCP resource reads",
        description=f"Fresh-eyes Codex lens with full {PRODUCT_NAME} context pointers and raw transcript access when broad analysis is requested.",
    ),
    Capability(
        id="resource.registry",
        kind="resource",
        title="Capability registry",
        layer=MCP_NAME,
        access="read",
        status="ready",
        auth="none",
        receipt="MCP read log",
        description=f"Machine-readable inventory of prompts, resources and tools exposed by {MCP_NAME}.",
    ),
    Capability(
        id="resource.workflow_roles",
        kind="resource",
        title="Workflow roles",
        layer=MCP_NAME,
        access="read",
        status="ready",
        auth="none",
        receipt="MCP read log",
        description="Raw role contracts and Codex bridge doctrine for agent orientation.",
    ),
    Capability(
        id="resource.role_config",
        kind="resource",
        title="Role/model config",
        layer=MCP_NAME,
        access="read",
        status="ready",
        auth="local filesystem",
        receipt="MCP read log",
        description="V1 role-to-adapter config. Roles stay stable; users choose model/provider adapters.",
    ),
    Capability(
        id="resource.transcript_latest",
        kind="resource",
        title="Latest Manager transcript",
        layer="CEO + Manager",
        access="read",
        status="ready",
        auth="local filesystem",
        receipt="MCP read log",
        description="Latest manager/chat transcript. Exposed as raw context, not Manager summary.",
    ),
    Capability(
        id="resource.latest_work",
        kind="resource",
        title="Latest work snapshot",
        layer="Transport state",
        access="read",
        status="ready",
        auth="local filesystem",
        receipt="transport-state output",
        description="Read-only snapshot from transport-state latest-work.",
    ),
    Capability(
        id="resource.transport_runs",
        kind="resource",
        title="Transport runs",
        layer="Transport",
        access="read",
        status="ready",
        auth="local filesystem",
        receipt="manager/state/transport/runs",
        description="Customer-local Transport run state for pinboard and Manager visibility.",
    ),
    Capability(
        id="resource.transport_events",
        kind="resource",
        title="Transport events",
        layer="Transport",
        access="read",
        status="ready",
        auth="local filesystem",
        receipt="manager/state/transport/events.jsonl",
        description="Append-only Transport event ledger: dispatch, heartbeat, stale, return and archive.",
    ),
    Capability(
        id="tool.registry_list",
        kind="tool",
        title=f"List {MCP_NAME} capabilities",
        layer=MCP_NAME,
        access="read",
        status="ready",
        auth="none",
        receipt="tool response",
        description="Returns capability inventory with layer, access mode, auth and receipt metadata.",
    ),
    Capability(
        id="tool.role_config",
        kind="tool",
        title="Read role/model config",
        layer=MCP_NAME,
        access="read",
        status="ready",
        auth="local filesystem",
        receipt="tool response",
        description="Returns the V1 role/model adapter config for PM and Agent Exec.",
    ),
    Capability(
        id="tool.codex_packet",
        kind="tool",
        title="Build Codex fresh-eyes packet",
        layer="CEO + Manager",
        access="read",
        status="ready",
        auth="local session / OAuth client",
        receipt="tool response",
        description="Builds raw context pointers and instructions for /codex or /codex full.",
    ),
    Capability(
        id="tool.codex_fresh_eyes",
        kind="tool",
        title="Run Codex fresh eyes",
        layer="CEO + Manager",
        access="adapter",
        status="ready",
        auth="local Codex OAuth/session",
        receipt="manager/agent-runs/codex-fresh-*",
        description="Assembles MCP context, calls local codex exec, and returns a one-shot fresh-eyes answer.",
    ),
    Capability(
        id="tool.codex_dispatch_packet",
        kind="tool",
        title="Build Codex PM dispatch packet",
        layer="Codex PM",
        access="dispatch",
        status="ready",
        auth="local session / OAuth client",
        receipt="tool response",
        description="Builds the bounded implementation packet for formal Codex PM dispatch without invoking execution.",
    ),
    Capability(
        id="tool.codex_dispatch",
        kind="tool",
        title="Dispatch Codex PM",
        layer="Transport -> Codex PM",
        access="dispatch",
        status="ready",
        auth="local Codex OAuth/session",
        receipt="manager/state/transport + manager/agent-runs/codex-dispatch-*",
        description="Compatibility rail for formal Codex PM dispatch, now backed by detached Transport watch/return/cleanup.",
    ),
    Capability(
        id="tool.transport_dispatch",
        kind="tool",
        title="Transport dispatch",
        layer="Transport",
        access="dispatch",
        status="ready",
        auth="local tool session / target OAuth",
        receipt="manager/state/transport/runs + events.jsonl",
        description="Creates a Transport run for Codex PM or Agent Exec, writes packet/receipt pointers, starts the watcher and returns run_id.",
    ),
    Capability(
        id="tool.chain_pm_then_agent",
        kind="tool",
        title="Chain PM then Agent",
        layer="Transport -> Codex PM -> Agent Exec",
        access="dispatch",
        status="ready",
        auth="local Codex OAuth + Claude OAuth",
        receipt="manager/state/transport/chains + manager/agent-runs/codex-dispatch-* + agent-exec-*",
        description="Sequenced PM -> Agent dispatch under one chain id with persistent chain-state and parent_run_id linkage.",
    ),
    Capability(
        id="tool.agent_exec_packet",
        kind="tool",
        title="Build Agent Exec packet",
        layer="Transport -> Agent Exec",
        access="dispatch",
        status="ready",
        auth="local adapter OAuth/session",
        receipt="tool response",
        description="Builds a model-agnostic T5 execution packet with parentRunId, intentId and sharedDoctrineRefs without invoking execution.",
    ),
    Capability(
        id="tool.transport_status",
        kind="tool",
        title="Transport status",
        layer="Transport",
        access="read",
        status="ready",
        auth="local filesystem",
        receipt="tool response",
        description="Reads non-hosted run status; hosted callers read customer-local .nogra records.",
    ),
    Capability(
        id="tool.transport_watch",
        kind="tool",
        title="Transport watch",
        layer="Transport",
        access="read",
        status="ready",
        auth="local filesystem",
        receipt="tool response",
        description="Convenience await for non-hosted Transport runs; hosted callers use local .nogra records.",
    ),
    Capability(
        id="tool.transport_return",
        kind="tool",
        title="Transport return",
        layer="Transport",
        access="read",
        status="ready",
        auth="local filesystem",
        receipt="tool response",
        description="Returns non-hosted report/output pointers; hosted callers use local .nogra records.",
    ),
    Capability(
        id="tool.transport_submit_report",
        kind="tool",
        title="Transport submit report",
        layer="Transport",
        access="write",
        status="ready",
        auth="local filesystem + dispatch-allocated run id",
        receipt="manager/agent-runs/<run>/report.md + receipt.json + events.jsonl",
        description="Non-hosted report return path; hosted Manager writes report/output into local .nogra records.",
    ),
    Capability(
        id="tool.transport_ack",
        kind="tool",
        title="Transport acknowledge",
        layer="Transport",
        access="write",
        status="ready",
        auth="local filesystem",
        receipt="manager/state/transport/events.jsonl",
        description="Marks a returned run acknowledged so cleanup can archive it.",
    ),
    Capability(
        id="tool.transport_cleanup",
        kind="tool",
        title="Transport cleanup",
        layer="Transport",
        access="write",
        status="ready",
        auth="local filesystem",
        receipt="manager/state/transport/archive + events.jsonl",
        description="Marks orphaned runs, archives acknowledged/old returns and rotates event history.",
    ),
    Capability(
        id="tool.transport_events",
        kind="tool",
        title="Transport events",
        layer="Transport",
        access="read",
        status="ready",
        auth="local filesystem",
        receipt="tool response",
        description="Reads the Transport event ledger for pinboard and Manager summaries.",
    ),
    Capability(
        id="tool.repo_status",
        kind="tool",
        title="Repo status snapshot",
        layer="State / observability",
        access="read",
        status="ready",
        auth="local filesystem",
        receipt="git output",
        description="Read-only git branch, head and dirty preview for context packets.",
    ),
)


def registry_payload() -> dict[str, object]:
    return {
        "name": os.environ.get("NOGRA_MCP_PACKAGE_NAME", "nogra-mcp"),
        "version": "v1.0.0",
        "releaseVersion": "v1.0.0",
        "principle": "Universal workflow tool-plane. Capabilities expose access; CEO/Manager own intent and GO.",
        "authModel": "Local logged-in clients / OAuth-first. No vendor API keys in workflow-core.",
        "capabilities": [capability.to_dict() for capability in CAPABILITIES],
    }
